export const ADD_INGREDIENT = "ADD_INGREDIENT"
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT"
export const SET_INGREDIENTS = "SET_INGREDIENTS"
export const FETCH_ERROR ='FETCH_ERROR'

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS'
export const PURCHASE_FAILED = 'PURCHASE_FAILED'
export const PURCHASE_LOADING = 'PURCHASE_LOADING'
export const PURCHASE_REDIRECT = 'PURCHASE_REDIRECT'

export const FETCH_ORDER_LOADING = 'FETCH_ORDER_LOADING'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL'

export const REMOVE_ORDER = 'REMOVE_ORDER'

export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT'

